### ISSUE TITLE
move this repo to stactools-packages org

### ISSUE THREAD

**Issue by hrodmn** [stactools-packages/noaa-hrrr#7]
When I cloned the template repo I published it to the developmentseed org. @wildintellect I saw that  you set up a [stactools package for nisar-sim](https://github.com/stactools-packages/nisar-sim) recently. Do you know how I can transfer this repo to the stactools-packages org?

**Comment by wildintellect** [comment]
@hrodmn there are 2 ways:
1. transfer ownership - requires an admin on our side who has create ability on stactools-package org
2. create a new repo on stactools org, push the code, and re-fork the DevSeed copy

For option 2 I think I have the ability to create repos on stactools org - looking to see who we might have for option 1.

**Comment by hrodmn** [comment]
@lossyrob @TomAugspurger do you have any suggestions for best practices on moving a repo over to the stactools-packages organization?

**Comment by TomAugspurger** [comment]
I've previously done it in two steps: one to a personal GitHub account of someone who has permission to create repos in stactools-packages, and from there to stactools-packages. IIRC, that bypasses the need to have someone who's an Admin (or has some elevated privileges) on both github.com/developmentseed and github.com/stactools-packages.

**Comment by hrodmn** [comment]
OK I think this should work :sweat_smile: :
1. @alukach (I see that you are an `owner` in the developmentseed organization) transfer ownership of this package to either the stactools-packages org or @wildintellect 
2. if @alukach cannot transfer it directly to stactools, transfer it to @wildintellect who can transfer ownership to stactools-packages

Nothing urgent here but it would be great to get this package into the stactools-packages org!

**Comment by alukach** [comment]
Hmm... 🤕
<img width="723" alt="image" src="https://github.com/developmentseed/noaa-hrrr/assets/897290/1d0fc1c5-eda2-4489-9799-055047439a2c">

Exactly as has been mentioned above.

@TomAugspurger so are you saying that if I transfer the repo to your username, you can transfer to `stactools-packages`?

**Comment by alukach** [comment]
Okay, transfer process in progress.

- [x] Transfer to @alukach
- [x] @alukach initiates transfer to @wildintellect
- [ ] @wildintellect accepts transfer of ownership
- [ ] @wildintellect transfers to https://github.com/stactools-packages

**Comment by hrodmn** [comment]
@TomAugspurger we finally got it moved over to the stactools-packages org but I have lost push privileges in the process. Are you able to add me to the package or, better yet, add someone from Development Seed to the stactools-packages org?

**Comment by TomAugspurger** [comment]
We'll need an Owner for that I think (I'm just a member). I'm not sure how that's managed.

@lossyrob is an owner and should be able to manage invites at https://github.com/stactools-packages/noaa-hrrr/settings/access.

I do think it's worth getting someone from DevSeed added as an owner.
